name: Benchmark Trigger

on:
  issue_comment:
    types: [ created ]
jobs:
  check-command:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      benchmark: ${{ steps.check.outputs.triggered }}
    steps:
    - name: Check Benchmark Trigger
      uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/benchmark'
        reaction: eyes
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' 
        
  benchmark:
    if: ${{ needs.check-command.outputs.benchmark == 'true' }}
    needs: check-command
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        include:
          - os: windows-2019
          - os: windows-2019
    steps:
    - name: Hello
      run: echo "Hello World"
      
  benchmark-compare:
    if: ${{ needs.check-command.outputs.benchmark == 'true' }}
    needs: benchmark
    runs-on: windows-2019
    steps:
    - name: GitHub Comment - Comparison
      run: |
        $message = "## Benchmark Comparison`r`n"
        $message += "Benchmarking comparison between this Pull Request and the comitted values at `benchmarks/results` `r`n`r`n"
        $message += "dcraw`r`n"
        $message += "``````ini `r`n" + "Test Data" + "`r`n ``````"
        $message += "`r`n`r`nthumbnail`r`n"
        $message += "``````ini `r`n" + "Test Data" + "`r`n ``````"
        echo $message
        echo "PR_COMMENT_COMPARISON<<EOF" >> $env:GITHUB_ENV
        echo "$message" >> $env:GITHUB_ENV
        echo "EOF" >> $env:GITHUB_ENV
#        echo "PR_COMMENT_COMPARISON=" + $message >> $env:GITHUB_ENV
        
    - name: GitHub Comment - Benchmark Results
      run: |
        $message = "## Benchmark Results`r`n"
        $message += "<details><summary>dcraw</summary><p>" + "test data" + "</p></details>`r`n"
        $message += "<details><summary>thumbnail</summary><p>" + "test data" + "</p></details>`r`n"
        echo $message
#        echo "PR_COMMENT_RESULTS=$message" >> $env:GITHUB_ENV

    - name: GitHub Comment - Post
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ env.PR_COMMENT_COMPARISON }}'
          })