name: Benchmark Trigger

on:
  issue_comment:
    types: [ created ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Check Benchmark Trigger
      uses: khan/pull-request-comment-trigger@master
      with:
        trigger: 'test'
        reaction: eyes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Hello
      if: steps.check.outputs.triggered == 'true'
      run: echo "Hello world"
