name: Benchmark

on:
  pull_request:
    branches: [ main ]
    types: [opened]

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            cuda: 'CUDA-11.4.0'
            visual_studio: 'Visual Studio 16 2019'
            benchmark: 'thumbnail'
          - os: windows-2019
            cuda: 'CUDA-11.4.0'
            visual_studio: 'Visual Studio 16 2019'
            benchmark: 'dcraw'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install CUDA
      env:
        cuda: ${{ matrix.cuda }}
        visual_studio: ${{ matrix.visual_studio }}
      shell: powershell
      run: .\build\cuda.ps1

    - name: Check NVCC
      shell: powershell
      run: |
        nvcc -V
        ls $env:CUDA_PATH
        ls $env:CUDA_PATH\bin
        ls $env:CUDA_PATH\include

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.x

    - name: Build
      run: dotnet build src/FileOnQ.Imaging.Raw/FileOnQ.Imaging.Raw.csproj -c Release

    - name: Benchmark
      run: dotnet run -c Release -b ${{ matrix.benchmark }}
      working-directory: ./benchmarks/tools

    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: Benchmark-${{ matrix.benchmark }}
        path: ./benchmarks/tools/BenchmarkDotNet.Artifacts/results

  benchmark-compare:
    needs: benchmark
    runs-on: windows-2019
    steps:
      - name: Clone fileonq/imaging.raw
        uses: actions/checkout@v2
        with:
          path: fileonq.imaging.raw
        
      - name: Clone dotnet/performance
        uses: actions/checkout@v2
        with:
          repository: dotnet/performance
          path: dotnet.performance
          
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: benchmark-artifacts
              
      - name: Compare - dcraw
        run: dotnet run  --base "../../../../fileonq.imaging.raw/benchmarks/results/dcraw" --diff "../../../../benchmark-artifacts/Benchmark-dcraw" --threshold 10% --top 10 > dcraw.output.txt
        working-directory: ./dotnet.performance/src/tools/ResultsComparer
        
      - name: Compare - thumbnail
        run: dotnet run  --base "../../../../fileonq.imaging.raw/benchmarks/results/thumbnail" --diff "../../../../benchmark-artifacts/Benchmark-thumbnail" --threshold 10% --top 10 > thumbnail.output.txt
        working-directory: ./dotnet.performance/src/tools/ResultsComparer
        
      - name: GitHub Comment - Comparison
        run: |
          $message = "## Benchmark Comparison
          $message = "Benchmarking comparison between this Pull Request and the comitted values at `benchmarks/results` `r`n`r`n"
          $message += "dcraw`r`n"
          $message += "```ini `r`n" + $(Get-Content "dcraw.output.txt" -raw) + "`r`n ``` "
          $message += "`r`n`r`nthumbnail"
          $message += "```ini `r`n" + $(Get-Content "thumbnail.output.txt" -raw) + "`r`n ``` "
          echo "PR_COMMENT_COMPARISON=$message" >> $env:GITHUB_ENV
        working-directory: ./dotnet.performance/src/tools/ResultsComparer
        
      - name: GitHub Comment - Benchmark Results
        run: |
          $message = "## Benchmark Results
          $message += "<details><summary>dcraw</summary><p>" + $(Get-Content "dcraw.md" -raw) + "</p></details>`r`n"
          $message += "<details><summary>thumbnail</summary><p>" + $(Get-Content "thumbnail.md" -raw) + "</p></details>`r`n"
          echo "PR_COMMENT_RESULTS=$message" >> $env:GITHUB_ENV
        
      - name: GitHub Comment - Post
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.PR_COMMENT_COMPARISON }}\r\n\r\n${{ env.PR_COMMENT_RESULTS }}'
      