name: Benchmark Trigger

on:
  issue_comment:
    types: [ created ]
jobs:
  check-command:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      benchmark: ${{ steps.check.outputs.triggered }}
    steps:
    - name: Check Benchmark Trigger
      uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/benchmark'
        reaction: eyes
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' 
        
  benchmark:
    if: ${{ needs.check-command.outputs.benchmark == 'true' }}
    needs: check-command
    runs-on: windows-2019
    steps:
    - name: Hello
      run: echo "Hello World"
      
  benchmark-compare:
    if: ${{ needs.check-command.outputs.benchmark == 'true' }}
    needs: benchmark
    runs-on: windows-2019
    steps:
    - name: Hello
      run: echo "Hello World"
